### ISSUE TITLE
https://getnebulo.com/ doesn't resolve

### ISSUE THREAD

**Issue by Roemerb** [undertideco/nebulo-scraper#1]
Title says it all!

<img width="1648" alt="screen shot 2017-06-15 at 15 41 25" src="https://user-images.githubusercontent.com/4710404/27184067-268a5650-51e1-11e7-8ced-35989ba22e85.png">

**Comment by jurvis** [comment]
welp that was embarrassing. thanks for the issue! 

![tzos8](https://user-images.githubusercontent.com/5944973/27184817-e417cade-5215-11e7-9baa-af5741dc07a8.gif)

**Comment by jurvis** [comment]
fixed: c030ed2
