### ISSUE TITLE
add support for The Netherlands

### ISSUE THREAD

**Issue by jurvis** [undertideco/nebulo-scraper#2]
as suggested by a friend, the Amsterdamians apparently care a lot about the air quality in their country.

let's write a scraper with this api: `https://data.openstate.eu/nl/dataset/landelijk-meetnet-luchtkwaliteit/resource/ad53c8ae-0d36-4a9f-9bd2-2e07e12fc9fe`

**Comment by duncanleo** [comment]
Based on random GitHub issues I've found floating about the Internet, this is a Timeseries API. A similar one is documented here - https://uk-air.defra.gov.uk/sos-ukair/static/doc/api-doc/

**Comment by duncanleo** [comment]
The API documentation site (which is some AWS URL) is down (and has probably been for a while)

**Comment by duncanleo** [comment]
Fixed in #11
